### ISSUE TITLE
Hot reload not work in version 0.11.2+2 ?

### ISSUE THREAD

**Issue by zhanglix** [ookami-kb/storybook_flutter#93]
same problem as #65 ,   

storybook_fluter info:
```
storybook_flutter:
    dependency: "direct dev"
    description:
      name: storybook_flutter
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.2+2"
```

flutter info:
```lang=bash
[✓] Flutter (Channel stable, 3.3.4, on macOS 12.6 21G115 darwin-x64, locale en-US)
    • Flutter version 3.3.4 on channel stable at /usr/local/Caskroom/flutter/3.0.5/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision eb6d86ee27 (11 days ago), 2022-10-04 22:31:45 -0700
    • Engine revision c08d7d5efc
    • Dart version 2.18.2
    • DevTools version 2.15.0
```
